name: Harness Integration

on:
  workflow_dispatch:

jobs:
  sanity-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Trigger Sanity Test on LambdaTest
        run: |
          echo "Triggering sanity tests on LambdaTest..."
          response=$(curl --silent --show-error --location \
            'https://test-manager-api.lambdatest.com/api/atm/v1/hyperexecute' \
            --header 'accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic ZGV2YW5zaHNpbmdodGVzdG11YWk6TFRfd1BjUGYxWTdFNmFGaXdDRGVNZGtaTUpHVEVqM1ZOMlJFQlhYZGd6ZnFjQjFKQWc=' \
            --data '{
              "test_run_id": "01M036FDXYNMV71108QF1E97VX",
              "concurrency": 1
            }')
          echo "Response received:"
          echo "$response"
